// <auto-generated />
using System;
using MascotaFeliz.app.persistencia.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MascotaFeliz.app.persistencia.Migrations
{
    [DbContext(typeof(EfAppContext))]
    [Migration("20211020031750_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MascotaFeliz.app.dominio.Empresa", b =>
                {
                    b.Property<int>("Nit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Nit")
                        .UseIdentityColumn();

                    b.Property<string>("DireccionEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DireccionEmpresa");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreEmpresa");

                    b.Property<string>("TelefonoEmpresa")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("TelefonoEmpresa");

                    b.HasKey("Nit");

                    b.ToTable("EmpresaDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMascota")
                        .UseIdentityColumn();

                    b.Property<string>("ColorOjos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ColorOjos");

                    b.Property<string>("ColorPiel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ColorPiel");

                    b.Property<int>("Estatura")
                        .HasColumnType("int")
                        .HasColumnName("Estatura");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("int")
                        .HasColumnName("FrecuenciaCardiaca");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("int")
                        .HasColumnName("FrecuenciaRespiratoria");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<string>("NombreMascota")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreMascota");

                    b.Property<int>("Peso")
                        .HasColumnType("int")
                        .HasColumnName("Peso");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdAnimal");

                    b.ToTable("MascotaDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Especialidad");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int")
                        .HasColumnName("IdMedico");

                    b.Property<int?>("Nit")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<int>("TarjetaProfecional")
                        .HasColumnType("int")
                        .HasColumnName("TarjetaProfecional");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("Nit");

                    b.ToTable("MedicosDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Direccion");

                    b.Property<int?>("IdMascota")
                        .HasColumnType("int");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("int")
                        .HasColumnName("IdPropietario");

                    b.Property<int?>("IdRegistroAtencion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdRegistroAtencion");

                    b.ToTable("PropietarioDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.RegistroAtencion", b =>
                {
                    b.Property<int>("IdRegistroAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRegistroAtencion")
                        .UseIdentityColumn();

                    b.Property<string>("DescripcionRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DescripcionRegistro");

                    b.Property<string>("FechaRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FechaRegistro");

                    b.Property<int?>("IdSolicitudAtencio")
                        .HasColumnType("int");

                    b.Property<string>("NombreRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreRegistro");

                    b.HasKey("IdRegistroAtencion");

                    b.HasIndex("IdSolicitudAtencio");

                    b.ToTable("RegistroAtencionDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.SolicitudAtencion", b =>
                {
                    b.Property<int>("IdSolicitudAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSolicitudAtencion")
                        .UseIdentityColumn();

                    b.Property<string>("DetalleSolicitud")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("DetalleSolicitud");

                    b.Property<string>("FechaSolicitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FechaSolicitud");

                    b.Property<int?>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int?>("IdMascota")
                        .HasColumnType("int");

                    b.Property<string>("NombreSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreSolicitud");

                    b.HasKey("IdSolicitudAtencion");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdMascota");

                    b.ToTable("SolicitudAtencionDb");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.TipoAnimal", b =>
                {
                    b.Property<int>("IdTipoAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTipoAnimal")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdTipoAnimal");

                    b.ToTable("TipoAnimal");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Mascota", b =>
                {
                    b.HasOne("MascotaFeliz.app.dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdAnimal");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Medicos", b =>
                {
                    b.HasOne("MascotaFeliz.app.dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdAnimal");

                    b.HasOne("MascotaFeliz.app.dominio.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("Nit");

                    b.Navigation("Empresa");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.Propietario", b =>
                {
                    b.HasOne("MascotaFeliz.app.dominio.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("IdMascota");

                    b.HasOne("MascotaFeliz.app.dominio.RegistroAtencion", "RegistroAtencion")
                        .WithMany()
                        .HasForeignKey("IdRegistroAtencion");

                    b.Navigation("Mascota");

                    b.Navigation("RegistroAtencion");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.RegistroAtencion", b =>
                {
                    b.HasOne("MascotaFeliz.app.dominio.SolicitudAtencion", "SolicitudAtencion")
                        .WithMany()
                        .HasForeignKey("IdSolicitudAtencio");

                    b.Navigation("SolicitudAtencion");
                });

            modelBuilder.Entity("MascotaFeliz.app.dominio.SolicitudAtencion", b =>
                {
                    b.HasOne("MascotaFeliz.app.dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdAnimal");

                    b.HasOne("MascotaFeliz.app.dominio.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("IdMascota");

                    b.Navigation("Mascota");

                    b.Navigation("TipoAnimal");
                });
#pragma warning restore 612, 618
        }
    }
}
